config/routes.rb
Rails.application.routes.draw do

  namespace :instructor do
    root 'top#index'
    get '/signup',to:'ir_users#new'
    post '/signup', to:'ir_users#create'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'
    post '/applys', to: 'applys#create'
    resources :ir_users
    resources :applys
  end

  namespace :organizer do
    root 'top#index'
    get '/signup', to:'org_users#new'
    post '/signup', to:'org_users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/event', to: 'events#new'
    post '/event', to: 'events#create'
    get '/event/:id', to: 'events#show'
    get '/confirm/:id', to: 'events#index2',as: 'confirm'
    patch '/confirm/:id', to: 'events#confirm'
    resources :org_users
    resources :events
  end

  namespace :customer do
    root 'top#index'
    get '/signup',to:'users#new'
    post '/signup', to:'users#create'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'
    resources :users
  end

end

app/models/ir_user.rb
class IrUser < ApplicationRecord
  before_save{self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,presence: true,length:{maximum:255},
            format:{with:VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password,presence: true,length:{minimum: 6}, allow_nil: true

  mount_uploader :image, ImageUploader
  has_many :events
end

app/controllers/instructor/applys_controller.rb
class Instructor::ApplysController < Instructor::Base
  def new
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @apply = Apply.new
    @apply.event_id = params[:event_id]
    @apply.ir_user_id = ir_current_user.id
    @apply.flag = true
    if @apply.save
      flash[:success] = "イベントに応募しました"
      redirect_to instructor_applys_path
    else
      flash[:danger] = "応募に失敗しました"
      redirect_to instructor_apply_path
    end
  end

end

app/controllers/instructor/base.rb
class Instructor::Base < ApplicationController
  layout 'instructor'
  include Instructor::SessionsHelper
end

app/controllers/instructor/ir_users_controller.rb
class Instructor::IrUsersController < Instructor::Base
  before_action :logged_in_user, only: [:edit,:update]
  before_action :correct_user, only: [:edit,:update]
 
  def show
    @ir_user = IrUser.find(params[:id])
  end
  
  def new
    @ir_user = IrUser.new
  end

  def create
    @ir_user = IrUser.new(ir_user_params)
    if @ir_user.save
      log_in @ir_user
      flash[:success] = "Welcomt to the YOGAWORLD!"
      redirect_to instructor_ir_user_url(@ir_user)
    else
      render 'new'
    end
  end

  def edit
    @ir_user = IrUser.find(params[:id])
  end

  def update
    @ir_user = IrUser.find(params[:id])
    if @ir_user.update_attributes(ir_user_params)
      flash[:success] = "Profile updated"
      redirect_to instructor_ir_user_url(@ir_user)
    else
      render 'edit'
    end
  end
  
  private

  def ir_user_params
    params.require(:ir_user).permit(:name,:email,:password,:password_confirmation,:introduction,:capabilities,:career,:image)
  end

  def logged_in_user
    unless ir_logged_in?
      flash[:danger] = "Please log in."
      redirect_to instructor_login_url
    end
  end

  def correct_user
    @ir_user = IrUser.find(params[:id])
    redirect_to(instructor_root_url) unless ir_current_user?(@ir_user)
  end
end

app/controllers/instructor/sessions_controller.rb
class Instructor::SessionsController < Instructor::Base
  def new
  end

  def create
    ir_user = IrUser.find_by(email: params[:session][:email].downcase)
    if ir_user && ir_user.authenticate(params[:session][:password])
      log_in ir_user
      redirect_to instructor_ir_user_url(ir_user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to instructor_root_path
  end
end

app/controllers/instructor/top_controller.rb
class Instructor::TopController < Instructor::Base
  def index
  end
end

app/helpers/instructor/applys_helper.rb
module Instructor::ApplysHelper
end

app/helpers/instructor/ir_users_helper.rb
module Instructor::IrUsersHelper
end

app/helpers/instructor/sessions_helper.rb
module Instructor::SessionsHelper
  def log_in(ir_user)
    session[:ir_user_id] = ir_user.id
  end

  def ir_current_user?(ir_user)
    ir_user == ir_current_user
  end

  def ir_current_user
    if session[:ir_user_id]
      @ir_current_user ||= IrUser.find_by(id: session[:ir_user_id])
    end
  end

  def ir_logged_in?
    !ir_current_user.nil?
  end

  def log_out
    session.delete(:ir_user_id)
    @ir_current_user = nil
  end
end

app/helpers/instructor/top_helper.rb
module Instructor::TopHelper
end

app/views/instructor/ir_users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@ir_user, url: instructor_ir_user_path) do |f| %>
      <%= render 'instructor/shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :introduction %>
      <%= f.text_area :introduction, class: 'form-control' %>    

      <%= f.label :capabilities %>
      <%= f.text_area :capabilities, class: 'form-control' %>    

      <%= f.label :career %>
      <%= f.text_area :career, class: 'form-control' %>
  
      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/instructor/ir_users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@ir_user, url: instructor_signup_path) do |f| %>
      <%= render 'instructor/shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name,class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email,class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password,class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation,class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/instructor/ir_users/show.html.erb
<% provide(:title, 'Profile') %>
<h1>Profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <label>name:</label>
      <%= @ir_user.name %>
    </div>

    <div class="form-group">
      <label>email:</label>
       <%= @ir_user.email %>
    </div>

    <div class="form-group">
      <label>introduction:</label>
      <p><%= @ir_user.introduction %></p>
    </div>

    <div class="form-group">
      <label>capabilities: </label>
      <%= @ir_user.capabilities %>
    </div>

    <div class="form-group">
      <label>career: </label>
      <%= @ir_user.career %>
    </div>

    <div class="form-group">
      <label>image: </label>
      <%= @ir_user.image %>
    </div>

  </div>
</div>