config/routes.rb
Rails.application.routes.draw do

  namespace :instructor do
    root 'top#index'
    get '/signup',to:'ir_users#new'
    post '/signup', to:'ir_users#create'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'
    post '/applys', to: 'applys#create'
    resources :ir_users
    resources :applys
  end

  namespace :organizer do
    root 'top#index'
    get '/signup', to:'org_users#new'
    post '/signup', to:'org_users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/event', to: 'events#new'
    post '/event', to: 'events#create'
    get '/event/:id', to: 'events#show'
    get '/confirm/:id', to: 'events#index2',as: 'confirm'
    patch '/confirm/:id', to: 'events#confirm'
    resources :org_users
    resources :events
  end

  namespace :customer do
    root 'top#index'
    get '/signup',to:'users#new'
    post '/signup', to:'users#create'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'
    resources :users
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :org_user
  has_many :ir_user
  has_many :apply
end

app/controllers/organizer/base.rb
class Organizer::Base < ApplicationController
  layout 'organizer'
  include Organizer::SessionsHelper
end

app/controllers/organizer/events_controller.rb
class Organizer::EventsController < Organizer::Base
  def index
    @events = Event.where(org_user_id: org_current_user.id) 
  end

  def new
    @event = Event.new
  end

  def create
    @event = org_current_user.events.new(event_params)
    if @event.save
      flash[:success] = 'Create Event'
      redirect_to organizer_events_url
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index2
    @event = Event.find(params[:id])
    @applys = Apply.where(event_id: @event.id)
  end

  def confirm
    @event = Event.find(params[:event_id])
    @apply = Apply.find(params[:apply_id])    
    if @apply.update_attribute(:c_flag,true)
      @event.update_attribute(:disclosed_page,true)
    flash[:success] = "承認しました"
    redirect_to organizer_confirm_path(@event)
    else
      render index2
    end
  end

end

private

def event_params
  params.require(:event).permit(:name, :date, :place, :term, :fee, :explanation, :comment, :comment2)
end

app/controllers/organizer/org_users_controller.rb
# before_action :logged_in_user, only: [:edit,:update]
# before_action :correct_user, only: [:edit,:update]

class Organizer::OrgUsersController < Organizer::Base
  def show
    @org_user = OrgUser.find(params[:id])
    # @events =  @org_user.events.paginate(page: params[:page])
  end

  def new
    @org_user = OrgUser.new
  end

  def create
    @org_user = OrgUser.new(org_user_params)
    if @org_user.save
      log_in @org_user
      flash[:success] = "Welcomt to the YOGAWORLD!"
      redirect_to organizer_org_user_url(@org_user)
    else
      render 'new'
    end
  end

  def edit
    @org_user = OrgUser.find(params[:id])
  end

  def update
    @org_user = OrgUser.find(params[:id])
    if @org_user.update_attributes(org_user_params)
      flash[:success] = "Profile updated"
      redirect_to organizer_org_user_url(@org_user)
    else
      render 'edit'
    end
  end

  private

    def org_user_params
      params.require(:org_user).permit(:name,:email,:password,
                      :password_confirmation,:introduction,:comment)
    end

    def logged_in_user
      unless org_logged_in?
        flash[:danger] = "Please log in."
        redirect_to organizer_login_url
      end
    end

    def correct_user
      @org_user = OrgUser.find(params[:id])
      redirect_to(organizer_root_url) unless org_current_user?(@org_user)
    end

end

app/controllers/organizer/sessions_controller.rb
class Organizer::SessionsController < Organizer::Base
  def new
  end

  def create
    org_user = OrgUser.find_by(email: params[:session][:email].downcase)
    if org_user && org_user.authenticate(params[:session][:password])
      log_in org_user
      redirect_to organizer_org_user_url(org_user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to organizer_root_path
  end
end

app/controllers/organizer/top_controller.rb
class Organizer::TopController < Organizer::Base 
  def index
  end
end

app/helpers/organizer/events_helper.rb
module Organizer::EventsHelper
end

app/helpers/organizer/org_users_helper.rb
module Organizer::OrgUsersHelper
end

app/helpers/organizer/sessions_helper.rb
module Organizer::SessionsHelper
  def log_in(org_user)
    session[:org_user_id] = org_user.id
  end

  def org_current_user?(org_user)
    org_user == org_current_user
  end

  def org_current_user
    if session[:org_user_id]
      @org_current_user ||= OrgUser.find_by(id: session[:org_user_id])
    end
  end

  def org_logged_in?
    !org_current_user.nil?
  end

  def log_out
    session.delete(:org_user_id)
    @org_current_user = nil
  end
end

app/helpers/organizer/top_helper.rb
module Organizer::TopHelper
end

app/views/organizer/events/confirm.html.erb
<% provide(:title, @event.name) %>
<h1>応募一覧</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% @applys.each do |apply| %>
    <ul>
      <%= link_to apply.ir_user_id,instructor_ir_user_path(apply) %>
      <%= link_to "承認",'#',class:"btn btn-primary"%>
    </ul>
  <% end %>
  </div>
</div>

app/views/organizer/events/index.html.erb
<% provide(:title, 'Events') %>
<h1>Event list</h1>

<%= link_to "Create Event",organizer_event_path, class: "btn btn-primary" %>


<% @events.each do |event| %>
  <ul>
    <%= link_to event.name,organizer_path(event) %>
    <%= link_to "応募あり",organizer_confirm_path(event),class:"btn btn-primary"%>
  </ul>
<% end %>

app/views/organizer/events/index2.html.erb
<% provide(:title, @event.name) %>
<h1>応募一覧</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% @applys.each do |apply| %>
    <ul>
      <%= link_to apply.ir_user_id,instructor_ir_user_path(apply) %>
      <%= link_to "承認",organizer_confirm_path(event_id: @event.id,apply_id: apply.id),method: :patch,class:"btn btn-primary"%>
    </ul>
  <% end %>
  </div>
</div>

app/views/organizer/events/new.html.erb
<% provide(:title, 'Event') %>
<h1>Event create</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: organizer_event_path) do |f| %>
     
      <%= f.label :eventname %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :eventdate %>
      <%= f.date_field :date , class: 'form-control' %>

      <%= f.label :place %>
      <%= f.text_field :place, class: 'form-control' %>

      <%= f.label :application_period　%>
      <%= f.date_field :term, class: 'form-control' %>    
      
      <%= f.label :fee %>
      <%= f.number_field :fee, class: 'form-control' %>

      <%= f.label :explanation %>
      <%= f.text_area :explanation, class: 'form-control' %>  

      <%= f.label :comment_for_instructor %>
      <%= f.text_area :comment, class: 'form-control' %> 

      <%= f.label :comment_for_User %>
      <%= f.text_area :comment2, class: 'form-control' %> 

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organizer/events/show.html.erb
<% provide(:title, @event.name) %>
<h1>イベント</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <label>name:</label>
      <%= @event.name %>
    </div>

    <div class="form-group">
      <label>date:</label>
       <%= @event.date %>
    </div>

    <div class="form-group">
      <label>place:</label>
      <p><%= @event.place %></p>
    </div>

    <div class="form-group">
      <label>term: </label>
      <%= @event.term %>
    </div>

    <div class="form-group">
      <label>fee: </label>
      <%= @event.fee %>
    </div>

    <div class="form-group">
      <label>explanation: </label>
      <%= @event.explanation %>
    </div>

    <div class="form-group">
      <label>comment_for_Instructor: </label>
      <%= @event.comment %>
    </div>

     <div class="form-group">
      <label>comment: </label>
      <%= @event.comment2 %>
    </div>

  </div>
</div>